"""Tests for `stw map` and stw/render.py (plan.md §8)."""

from __future__ import annotations

import json

from helpers import seed

from stw.db import connect
from stw.render import render_map, write_map
from stw.workspace import Workspace


def test_render_map_header_and_grouping(ws_dir):
    ws = seed(
        ws_dir,
        {
            "research/rag.md": (
                "---\nabout: retrieval strategies\ntags: [research]\n---\n\n"
                "# RAG\n\n## Chunking\n\nbody\n\n## Evaluation\n\nbody\n"
            ),
            "notes/eval-log.md": "---\nabout: dated experiment notes\ntags: [log]\n---\n\n# Log\n",
        },
    )
    conn = connect(ws.index_path)
    try:
        content = render_map(ws, conn)
    finally:
        conn.close()

    assert content.startswith("<!-- generated by stw · do not edit -->\n")
    assert "# Workspace map" in content
    assert "files ·" in content and "links ·" in content and "broken ·" in content
    assert "## notes/" in content
    assert "## research/" in content
    assert "**rag.md** — retrieval strategies `#research`" in content
    assert "Chunking · Evaluation" in content
    assert "**eval-log.md** — dated experiment notes `#log`" in content


def test_render_map_link_counts(ws_dir):
    ws = seed(
        ws_dir,
        {
            "a.md": "# A\n\n[[b]]\n",
            "b.md": "# B\n\nno links back\n",
        },
    )
    conn = connect(ws.index_path)
    try:
        content = render_map(ws, conn)
    finally:
        conn.close()
    assert "→ 1 out, 0 back" in content  # a.md
    assert "→ 0 out, 1 back" in content  # b.md


def test_render_map_db_artifact_degrades_gracefully(ws_dir):
    ws = Workspace.at(ws_dir)
    conn = connect(ws.index_path, create=True)
    try:
        conn.execute(
            "INSERT INTO files(path, kind, size, mtime_ns, sha256, title, about, tags, frontmatter, indexed_at) "
            "VALUES('data/experiments.db','db',0,0,'x',NULL,NULL,'[]','{}','now')"
        )
        # no rows in `tables` -- must not raise, must degrade
        content = render_map(ws, conn)
    finally:
        conn.close()
    assert "**experiments.db**" in content


def test_render_map_db_artifact_with_tables(ws_dir):
    ws = Workspace.at(ws_dir)
    conn = connect(ws.index_path, create=True)
    try:
        conn.execute(
            "INSERT INTO files(path, kind, size, mtime_ns, sha256, title, about, tags, frontmatter, indexed_at) "
            "VALUES('data/experiments.db','db',0,0,'x',NULL,NULL,'[]','{}','now')"
        )
        conn.execute(
            "INSERT INTO tables(db_path, table_name, row_count, columns) VALUES(?,?,?,?)",
            ("data/experiments.db", "runs", 1204, "[]"),
        )
        conn.execute(
            "INSERT INTO tables(db_path, table_name, row_count, columns) VALUES(?,?,?,?)",
            ("data/experiments.db", "configs", 38, "[]"),
        )
        content = render_map(ws, conn)
    finally:
        conn.close()
    # rendered alphabetically by table name
    assert "**experiments.db** — configs (38) · runs (1,204)" in content


def test_render_map_under_filters_but_header_stays_global(ws_dir):
    ws = seed(ws_dir, {"a/x.md": "# X\n", "b/y.md": "# Y\n"})
    conn = connect(ws.index_path)
    try:
        content = render_map(ws, conn, under="a")
    finally:
        conn.close()
    assert "## a/" in content
    assert "## b/" not in content
    assert "2 files" in content  # header counts the whole workspace, not the filtered view


def test_render_map_depth(ws_dir):
    ws = seed(ws_dir, {"a/b/c.md": "# C\n"})
    conn = connect(ws.index_path)
    try:
        d1 = render_map(ws, conn, depth=1)
        d2 = render_map(ws, conn, depth=2)
    finally:
        conn.close()
    assert "## a/" in d1
    assert "## a/b/" in d2


def test_write_map_writes_file(ws_dir):
    ws = seed(ws_dir, {"notes/x.md": "# X\n"})
    conn = connect(ws.index_path)
    try:
        path = write_map(ws, conn)
    finally:
        conn.close()
    assert path == ws_dir / "map.md"
    assert path.exists()
    assert path.read_text().startswith("<!-- generated by stw · do not edit -->\n")


def test_map_command_prints_to_stdout(cli, ws_dir):
    seed(ws_dir, {"notes/x.md": "# X\n"})
    r = cli("map")
    assert r.returncode == 0
    assert "<!-- generated by stw" in r.stdout
    assert not (ws_dir / "map.md").exists()  # printing alone must not write the file


def test_map_command_write_flag(cli, ws_dir):
    seed(ws_dir, {"notes/x.md": "# X\n"})
    r = cli("map", "--write")
    assert r.returncode == 0
    assert (ws_dir / "map.md").exists()
    assert "map.md" in r.stdout


def test_map_command_json(cli, ws_dir):
    seed(ws_dir, {"notes/x.md": "# X\n"})
    r = cli("--json", "map")
    data = json.loads(r.stdout)
    assert "<!-- generated by stw" in data["content"]
