"""map.md renderer (plan.md §8).

map.md is the agent's orientation file — what it reads first to know what it
knows. Rendering only ever reads from the index (never re-parses files on
disk), so it stays cheap no matter how large the workspace gets.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from . import index as index_mod
from .workspace import Workspace


def render_map(
    ws: Workspace,
    conn: sqlite3.Connection,
    depth: int | None = None,
    under: str | None = None,
) -> str:
    """Render the workspace map as markdown. Pure function of the index."""
    depth = depth if depth is not None else int(ws.config["map"].get("depth", 1))

    total_files = conn.execute("SELECT COUNT(*) c FROM files").fetchone()["c"]
    total_links = conn.execute("SELECT COUNT(*) c FROM links").fetchone()["c"]
    broken = conn.execute("SELECT COUNT(*) c FROM links WHERE resolved = 0").fetchone()["c"]

    rows = list(conn.execute("SELECT path, kind, about, tags FROM files ORDER BY path"))
    if under:
        u = under.rstrip("/")
        rows = [r for r in rows if r["path"] == u or r["path"].startswith(u + "/")]

    groups: dict[str, list[sqlite3.Row]] = {}
    for r in rows:
        parts = Path(r["path"]).parent.parts
        key = "/".join(parts[:depth]) if parts else ""
        groups.setdefault(key, []).append(r)

    lines = [
        "<!-- generated by stow · do not edit -->",
        "# Workspace map",
        f"{total_files} files · {total_links} links · {broken} broken · "
        f"updated {index_mod.now_iso()}",
        "",
    ]

    for key in sorted(groups):
        lines.append(f"## {key + '/' if key else './'}")
        for r in sorted(groups[key], key=lambda r: r["path"]):
            if r["kind"] == "db":
                lines.append(_db_bullet(conn, r))
            else:
                lines.append(_md_bullet(conn, r))
                heads = _top_headings(conn, r["path"])
                if heads:
                    lines.append(f"  {' · '.join(heads)}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def _md_bullet(conn: sqlite3.Connection, r: sqlite3.Row) -> str:
    name = Path(r["path"]).name
    about = r["about"] or ""
    tags = json.loads(r["tags"] or "[]")
    tag_str = " ".join(f"`#{t}`" for t in tags)

    bullet = f"- **{name}**"
    if about:
        bullet += f" — {about}"
    if tag_str:
        bullet += f" {tag_str}"

    out = conn.execute(
        "SELECT COUNT(*) c FROM links WHERE src_path = ?", (r["path"],)
    ).fetchone()["c"]
    back = conn.execute(
        "SELECT COUNT(*) c FROM links WHERE target_path = ? AND src_path != ?",
        (r["path"], r["path"]),
    ).fetchone()["c"]
    if out or back:
        bullet += f" → {out} out, {back} back"
    return bullet


def _db_bullet(conn: sqlite3.Connection, r: sqlite3.Row) -> str:
    name = Path(r["path"]).name
    tbls = list(
        conn.execute(
            "SELECT table_name, row_count FROM tables WHERE db_path = ? ORDER BY table_name",
            (r["path"],),
        )
    )
    if not tbls:
        return f"- **{name}**" + (f" — {r['about']}" if r["about"] else "")
    tstr = " · ".join(f"{t['table_name']} ({t['row_count']:,})" for t in tbls)
    return f"- **{name}** — {tstr}"


def _top_headings(conn: sqlite3.Connection, path: str) -> list[str]:
    return [
        r["text"]
        for r in conn.execute(
            "SELECT text FROM headings WHERE path = ? AND level = 2 ORDER BY line_start",
            (path,),
        )
    ]


def write_map(ws: Workspace, conn: sqlite3.Connection) -> Path:
    """Render the default map and write it to map.md. Fast, side-effect free otherwise."""
    content = render_map(ws, conn)
    path = ws.root / "map.md"
    path.write_text(content, encoding="utf-8")
    return path
